package Aufgabe_4;

public class Exceptionzz {

    public static void main(String[] args) throws Ibimez {

        throw new Ibimez();
        //hier gibt es eine neue exception aus
    }
}
